"""Narrow exercised 5.14.0 render API; no arbitrary untyped vendor tree."""

from PIL.Image import Image

class PdfBitmap:
    def close(self) -> None: ...
    def to_pil(self) -> Image: ...

class PdfPage:
    def close(self) -> None: ...
    def get_size(self) -> tuple[float, float]: ...
    def render(self, *, scale: float) -> PdfBitmap: ...

class PdfDocument:
    def __init__(self, input_data: bytes) -> None: ...
    def close(self) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> PdfPage: ...
