"""Inspected 2.11.0 worker-only native binding surface."""

from typing import TypedDict
from PIL.Image import Image

class Orientation(TypedDict):
    orient_deg: int
    orient_conf: float
    script_name: str
    script_conf: float

class RIL:
    TEXTLINE: int

class PyResultIterator:
    def GetUTF8Text(self, level: int) -> str: ...
    def BoundingBox(self, level: int) -> tuple[int, int, int, int] | None: ...
    def Confidence(self, level: int) -> float: ...
    def Next(self, level: int) -> bool: ...

class PyTessBaseAPI:
    def __init__(self, *, path: str, lang: str, psm: int) -> None: ...
    def SetImage(self, image: Image) -> None: ...
    def Recognize(self) -> bool: ...
    def GetIterator(self) -> PyResultIterator | None: ...
    def DetectOrientationScript(self) -> Orientation | None: ...
    def End(self) -> None: ...

def get_languages(path: str) -> tuple[str, list[str]]: ...

def tesseract_version() -> str: ...
